// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA85b_jkEAildBXET_ClIYV9c8cnOD3AuM',
    appId: '1:944236080391:web:2cb52971ec92a4b924a9a2',
    messagingSenderId: '944236080391',
    projectId: 'comp2750-week9',
    authDomain: 'comp2750-week9.firebaseapp.com',
    storageBucket: 'comp2750-week9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi3K_FF1HHmhSr27IIIBWjYosI0n5Vymw',
    appId: '1:944236080391:android:8e5412389ab3caff24a9a2',
    messagingSenderId: '944236080391',
    projectId: 'comp2750-week9',
    storageBucket: 'comp2750-week9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkpQMutShSrM-u7gnW_RhC0hDpz56SDds',
    appId: '1:944236080391:ios:3cc4266d2390874f24a9a2',
    messagingSenderId: '944236080391',
    projectId: 'comp2750-week9',
    storageBucket: 'comp2750-week9.firebasestorage.app',
    iosBundleId: 'com.example.travelExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkpQMutShSrM-u7gnW_RhC0hDpz56SDds',
    appId: '1:944236080391:ios:3cc4266d2390874f24a9a2',
    messagingSenderId: '944236080391',
    projectId: 'comp2750-week9',
    storageBucket: 'comp2750-week9.firebasestorage.app',
    iosBundleId: 'com.example.travelExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA85b_jkEAildBXET_ClIYV9c8cnOD3AuM',
    appId: '1:944236080391:web:ece105b1f87fec0f24a9a2',
    messagingSenderId: '944236080391',
    projectId: 'comp2750-week9',
    authDomain: 'comp2750-week9.firebaseapp.com',
    storageBucket: 'comp2750-week9.firebasestorage.app',
  );

}